# Generated by Django 6.0.1 on 2026-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='problem_solved',
            field=models.IntegerField(default=0),
        ),
    ]
