# Generated by Django 6.0.1 on 2026-02-01 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_problem_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
